name: Deploy to Production
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: GitHub Action Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          # Deploy vars
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: 'wholesaleprd'
          # Deploy Options
          REMOTE_PATH: "wp-content/themes/wholesale/"
          CACHE_CLEAR: TRUE
